name: sync-docs

# Run workflow for every push to the `main` branch
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Run GitHub Action to sync docs in `documentation` directory
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          rdme: docs ./documentation --key=${{ secrets.README_API_KEY }} --version=1.0

      - name: Set merge status on failure
        if: failure()
        run: echo "::error::Vale check failed. Please fix the issues before merging." && exit 1
        
